# Generated by Django 6.1 on 2026-09-01 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0002_attendance_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Mfano: Mtihani wa Muhula wa Kwanza 2026', max_length=150)),
                ('exam_type', models.CharField(choices=[('MID_TERM', 'Mid-Term'), ('TERMINAL', 'Terminal'), ('ANNUAL', 'Annual')], max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Matokeo yakishachapishwa wazazi wanaweza kuyaona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, help_text='Mfano: A, B, C, D, F', max_length=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.examsubject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'unique_together': {('exam_subject', 'student')},
            },
        ),
    ]
